//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FontEdit.rc
//
#define IDD_FONTEDIT_DIALOG             102
#define IDR_MAINFRAME                   128
#define ICN_MAIN                        130
#define IDB_TILE                        132
#define IDC_HEIGHT                      1000
#define IDC_WIDTH                       1001
#define IDC_LETNUM                      1003
#define IDC_PANUP                       1004
#define IDC_PANDOWN                     1005
#define IDC_PANLEFT                     1006
#define IDC_PANRIGHT                    1007
#define IDC_LETCHAR                     1008
#define IDC_LETTER                      1009
#define IDC_COPY                        1010
#define IDC_PASTE                       1011
#define IDC_CLEAR                       1012
#define IDC_UNDO                        1013
#define IDC_LOAD                        1014
#define IDC_SAVE                        1015
#define IDC_ABOUT                       1016
#define IDC_HEIGHTDOWN                  1020
#define IDC_HEIGHTUP                    1021
#define IDC_WIDTHDOWN                   1022
#define IDC_WIDTHUP                     1023
#define IDC_LETTERDOWN                  1024
#define IDC_LETTERUP                    1025
#define IDC_BUTTON1                     1026
#define IDC_OUTLINE                     1026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
